myproject/blogs/views.py
from myproject import db
from flask import render_template, request, redirect, Blueprint, flash, url_for, abort
from flask_login import current_user, login_required
from myproject.models import Blog, Comment
from myproject.blogs.forms import BlogPostForm


blogs_blueprint = Blueprint('blogs', __name__, template_folder='templates/blogs')


@blogs_blueprint.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = Blog(
            title=form.title.data,
            text=form.text.data,
            user_id=current_user.id
        )
        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created!')
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)


# View Blog
@blogs_blueprint.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post_query = Blog.query.get_or_404(blog_post_id)
    comments = Comment.query.filter_by(blog_id=blog_post_id).all()
    return render_template('blog_post.html',
                           title=blog_post_query.title,
                           date=blog_post_query.date,
                           post=blog_post_query,
                           comments=comments)


# Update
@blogs_blueprint.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(blog_post_id):
    blog_post = Blog.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data

        db.session.commit()  # Just update no need to add!
        flash('Blog Post Updated!')
        return redirect(url_for('blogs.blog_post', blog_post_id=blog_post.id))
        # We provided needed id in url by passing parameter with redirect
    elif request.method == 'GET':
        form.text.data = blog_post.text
        form.title.data = blog_post.title

    return render_template('create_post.html', title='Updating', form=form)


# Delete
@blogs_blueprint.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = Blog.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted!')
    return redirect(url_for('core.index'))

myproject/comments/views.py
from myproject import db
from flask_login import current_user, login_required
from flask import redirect, render_template, url_for, Blueprint, abort, request, flash
from myproject.models import Comment
from .forms import CommentForm

comments_blueprint = Blueprint('comments', __name__, template_folder='templates/comments')


# Create
@comments_blueprint.route('/<blog_post_id>/create_comment', methods=['GET', 'POST'])
@login_required
def create_comment(blog_post_id):
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(
            text=form.text.data,
            user_id=current_user.id,
            blog_id=blog_post_id
        )
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('blogs.blog_post', blog_post_id=blog_post_id))
    return render_template('create_comment.html', form=form)


@comments_blueprint.route('/<comment_id>', methods=['GET', 'POST'])
@login_required
def update_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.comment_author != current_user:
        abort(403)

    form = CommentForm()
    if form.validate_on_submit():
        comment.text = form.text.data
        db.session.commit()
        return redirect(url_for('blogs.blog_post', blog_post_id=comment.blog_id))
    elif request.method == 'GET':
        form.text.data = comment.text

    return render_template('create_comment.html', form=form)


@comments_blueprint.route('/<comment_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.comment_author != current_user:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted!')
    return redirect(url_for('blogs.blog_post', blog_post_id=comment.blog_id))

myproject/core/views.py
from flask import render_template, request, Blueprint
from myproject.models import Blog

cores_blueprint = Blueprint('core', __name__)


@cores_blueprint.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = Blog.query.order_by(Blog.date.desc()).paginate(page=page, per_page=8)
    return render_template('index.html', blog_posts=blog_posts)


@cores_blueprint.route('/info')
def info():
    return render_template('info.html')

myproject/users/views.py
from flask import render_template, redirect, url_for, flash, request, Blueprint, abort
from flask_login import login_required, login_user, current_user, logout_user
from myproject import db
from myproject.models import User, Blog
from myproject.users.forms import LoginForm, RegisterForm, UpdateUserForm, UpdateImageForm
from myproject.users.picture_handler import add_profile_pic


users_blueprint = Blueprint('users', __name__)


@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You are logged out!')
    return redirect(url_for('core.index'))


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            username=form.username.data.lower(),
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()
        flash('Thank you for registration!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                flash('Login Success!')

                next = request.args.get('next')
                if next is None or not next[0] == '/':
                    next = url_for('core.index')

                return redirect(next)
    return render_template('login.html', form=form)


@users_blueprint.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    user_form = UpdateUserForm()
    image_form = UpdateImageForm()
    if user_form.validate_on_submit():
        current_user.username = user_form.username.data.lower()
        current_user.email = user_form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        user_form.username.data = current_user.username
        user_form.email.data = current_user.email

    if image_form.validate_on_submit():
        if image_form.picture.data:  # If user uploaded pic
            username = current_user.username
            pic = add_profile_pic(image_form.picture.data, username)
            current_user.profile_image = pic
            db.session.commit()
            flash('User Image Updated!')
            return redirect(url_for('users.account'))

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, user_form=user_form, image_form=image_form)


@users_blueprint.route('/account/delete', methods=['GET', 'POST'])
@login_required
def delete_account():
    user = User.query.get_or_404(current_user.id)
    if user.id != current_user.id:
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('Account has been deleted!')
    return redirect(url_for('core.index'))


@users_blueprint.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)  # Important for pagination
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = Blog.query.filter_by(author=user).order_by(Blog.date.desc()).paginate(page=page,
                                                                                       per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

myproject/templates/account.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <div align="center">
            <h1>Welcome {{ current_user.username|capitalize }}</h1>
            <img align="center"
                 src="{{ profile_image }}"
                 alt="Profile picture"
                 width="200"
                 height="200">
        </div>
    </div>
    <div class="container">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ image_form.hidden_tag() }}
            <div class="mb-3">
                {{ image_form.picture.label(class="form-label") }} {{ image_form.picture(class="form-control") }}
                <div class="form-text">
                    Picture must be .jpg or .png
                </div>
            </div>
            <div class="mb-3">
                {{ image_form.submit(class="btn btn-warning") }}
            </div>
        </form>
        <form method="POST" action="">
            {{ user_form.hidden_tag() }}
            <div class="mb-3">
                {{ user_form.username.label(class="form-label") }} {{ user_form.username(class="form-control") }}
                {% if user_form.username.errors %}
                  <ul class="errors mt-2">
                    {% for error in user_form.username.errors %}
                      <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                  </ul>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ user_form.email.label(class="form-label") }} {{ user_form.email(class="form-control") }}
                {% if user_form.email.errors %}
                   <ul class="errors mt-2">
                    {% for error in user_form.email.errors %}
                      <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                  </ul>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ user_form.submit(class="btn btn-primary") }}
                <button type="button"
                        class="btn btn-outline-danger"
                        data-bs-toggle="modal"
                        data-bs-target="#del_account">
                    Delete Account
                </button>
            </div>
        </form>

    </div>
    <div class="modal" tabindex="-1" id="del_account">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Delete Account?</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <h5>Are you sure you want to delete the account?</h5>
              <p>This change is permanent!</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>

              <form action="{{ url_for('users.delete_account') }}">
                  <input type="submit" value="Delete" class="btn btn-danger">
              </form>

          </div>
        </div>
      </div>
    </div>
{% endblock %}

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>Pythonisti</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-primary bg-warning">
      <div class="container">
       
        <a class="navbar-brand navbar_link" href="{{ url_for('core.index') }}">
          <img src="{{ url_for('static', filename='python_logo.png') }}" alt="Pythonisti Logo Icon" width="35" height="35">
            Pythonisti
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
              {% if current_user.is_authenticated %}
                <li class="nav-item justify-content-end">
                  <a class="nav-link navbar_link" href="{{ url_for('blogs.create_post') }}">Create Post</a>
                </li>
                <li class="nav-item justify-content-end">
                  <a class="nav-link navbar_link" href="{{ url_for('messages.inbox') }}">Inbox</a>
                </li>
                <li class="nav-item justify-content-end">
                  <a class="nav-link navbar_link" href="{{ url_for('users.account') }}">Account</a>
                </li>
                <li class="nav-item justify-content-end">
                  <a class="nav-link navbar_link" href="{{ url_for('core.info') }}">About/Api</a>
                </li>
                <li class="nav-item justify-content-end">
                  <a class="nav-link navbar_link" href="{{ url_for('users.logout') }}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item justify-content-end">
                    <a class="nav-link navbar_link" href="{{ url_for('users.login') }}">Login</a>
                </li>
                <li class="nav-item justify-content-end">
                    <a class="nav-link navbar_link" href="{{ url_for('users.register') }}">Register</a>
                </li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col mt-4">
                {% for message in get_flashed_messages() %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            {% block content %}

            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

myproject/templates/blog_post.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
        <h1>{{ title }}</h1>
        <h2>
            Written by:
            <img src="{{ url_for('static', filename='profile_pics/'+post.author.profile_image) }}" height="50" width="50" alt="Profile Picture">
            {{ post.author.username|capitalize }}
        </h2>
        <h4>Published: {{ date.strftime("%d-%B-%Y") }}</h4>
        <p>{{ post.text }}</p>

        {% if post.author == current_user %}
            <div>
                <a href="{{ url_for('comments.create_comment', blog_post_id=post.id) }}" class="btn btn-outline-primary">Write Comment</a>
                <a href="{{ url_for('blogs.update_post', blog_post_id=post.id) }}" class="btn btn-primary">Update Post</a>
                <button type="button"
                        class="btn btn-outline-danger"
                        data-bs-toggle="modal"
                        data-bs-target="#del_modal">
                    Delete Post
                </button>
            </div>
        {% else %}
            <div>
                <a href="{{ url_for('comments.create_comment', blog_post_id=post.id) }}" class="btn btn-outline-primary">Write Comment</a>
            </div>
        {% endif %}
    </div>

    <br>

    <div class="modal" tabindex="-1" id="del_modal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Delete Post?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete the post?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>

              <!--   Ovo smo mi ubacili da bi prosledili korisnika do delete view kako bi obrisali post!   -->
              <form action="{{ url_for('blogs.delete_post', blog_post_id=post.id) }}">
                  <input type="submit" value="Delete" class="btn btn-danger">
              </form>

          </div>
        </div>
      </div>
    </div>

    {% for comment in comments %}
    <div class="jumbotron">
        <h3>
            Written by:
            <img src="{{ url_for('static', filename='profile_pics/'+comment.comment_author.profile_image) }}" height="30" width="30" alt="Profile Picture">
            {{ comment.comment_author.username|capitalize }}
        </h3>
        <h4>Published: {{ date.strftime("%d-%B-%Y") }}</h4>
        <p>{{ comment.text }}</p>
    </div>
        {% if comment.comment_author == current_user %}
            <div>
                <a href="{{ url_for('comments.update_comment', comment_id=comment.id) }}" class="btn btn-outline-primary">Update Comment</a>
                <button type="button"
                        class="btn btn-outline-danger"
                        data-bs-toggle="modal"
                        data-bs-target="#del_comment">
                    Delete Comment
                </button>

        <div class="modal" tabindex="-1" id="del_comment">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Delete Comment?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>Are you sure you want to delete the comment?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>

                  <form action="{{ url_for('comments.delete_comment', comment_id=comment.id) }}">
                      <input type="submit" value="Delete" class="btn btn-danger">
                  </form>

              </div>
            </div>
          </div>
        </div>
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

myproject/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>Pythonisti Blog and much more!</h1>
  </div>

  {% for post in blog_posts.items %}
  <a href="{{ url_for('blogs.blog_post', blog_post_id=post.id) }}">
    <div class="card card_post">
      <div class="card-body">
        <h2>
          {{ post.title }}
        </h2>
        <label>Writtent By:</label>
        
           <img src="{{ url_for('static', filename='profile_pics/'+post.author.profile_image) }}" height="30" width="30" alt="Profile Picture">
            <a class='author_name_link' href="{{ url_for('users.user_posts', username=post.author.username) }}">
                {{ post.author.username|capitalize }}
            </a>
        <p>Published on: {{ post.date.strftime("%d-%B-%Y") }}</p>
        <a href="{{ url_for('blogs.blog_post', blog_post_id=post.id) }}" class="btn btn-outline-primary blue_btn">
          Read Blog Post
        </a>
      </div>
    </div>
    <br>
  </a>
  {% endfor %}
  <nav aria-label="Page Navigation example">
     <ul class="pagination justify-content-center">

       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
          <a href="{{ url_for('core.index', page=page_num) }}" class="page-link">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a href="{{ url_for('core.index', page=page_num) }}" class="page-link">{{ page_num }}</a>
        </li>
        {% endif %}
       {% endfor %}
    </ul>
  </nav>
{% endblock %}

myproject/templates/info.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>About ME</h1>
    <p>Hello! My name is Nemanja Davidović, and I'm a Python Software Developer.</p>
    <p class="mb-3">I like to build and learn new things. This project is built using Flask Library. It has many features: </p>
    <ul>
      <li>Blog posting and commenting</li>
      <li>User account</li>
      <li>Authentication system</li>
      <li>Mail base app</li>
    </ul>

    <p>If you want to see more of my projects hop on to my<a class="check_message_link" href="https://nemanjadavidovic.pythonanywhere.com/" target="_blank">Portfolio site!</a></p>
  </div>
<div class="jumbotron mt-4">
  <h2 style="color: var(--dark_blue);">API</h2>
  <p>To see a list of blogs go to this endpoint <strong>/api/blogs</strong></p>
  <p>For specific blog go to this endpoint <strong>/api/blog/{int:id}</strong></p>
</div>
{% endblock %}

myproject/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>Login</h1>
    <form method="POST">
      {{ form.hidden_tag() }}
      <div class="mb-3">
        {{ form.email.label(class="form-label") }} {{ form.email(class="form-control") }}
      </div>
      <div class="mb-3">
        {{ form.password.label(class="form-label") }} {{ form.password(class="form-control") }}
      </div>
      <div class="mb-3">
        {{ form.submit(class='btn btn-primary') }}
      </div>
    </form>
  </div>
{% endblock %}

myproject/templates/register.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>Registration</h1>
    <form method="POST">
      {{ form.hidden_tag() }}
      <div class="mb-3">
        {{ form.email.label(class="form-label") }} {{ form.email(class="form-control") }}
        {% if form.email.errors %}
          <ul class="errors mt-2">
            {% for error in form.email.errors %}
              <li class="text-danger">{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="mb-3">
        {{ form.username.label(class="form-label") }} {{ form.username(class="form-control") }}
        <div class="form-text">
          Your username must be 4-24 characters long
        </div>
        {% if form.username.errors %}
          <ul class="errors mt-2">
            {% for error in form.username.errors %}
              <li class="text-danger">{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="mb-3">
        {{ form.password.label(class="form-label") }} {{ form.password(class="form-control") }}
        <div class="form-text">
          Your password must be 8-24 characters long
        </div>
        {% if form.password.errors %}
          <ul class="errors mt-2">
            {% for error in form.password.errors %}
              <li class="text-danger">{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="mb-3">
        {{ form.confirm_pass.label(class="form-label") }} {{ form.confirm_pass(class="form-control") }}
      </div>
      <div class="mb-3">
        {{ form.submit(class='btn btn-primary') }}
      </div>
    </form>
  </div>
{% endblock %}

myproject/templates/user_blog_posts.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div align='center' class="jumbotron">
      <h1>Welcome to {{ user.username|capitalize }}'s posts</h1>
      <img src="{{ url_for('static', filename='profile_pics/'+user.profile_image) }}" alt="profile picture" width="150" height="150">
    </div>
    {% for post in blog_posts.items %}
      <h4><a href="{{ url_for('blogs.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h4>
      Written By: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username|capitalize }}</a>
      <p class="text-muted mb-2">Published on: {{ post.date.strftime("%d-%B-%Y") }}</p>
      <div class="post_comments">
        <p>{{ post.text }}</p>
      </div>
      <hr>
    {% endfor %}
  </div>
  <nav aria-label="Page Navigation example">
     <ul class="pagination justify-content-center">

       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
          <a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" class="page-link">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" class="page-link">{{ page_num }}</a>
        </li>
        {% endif %}
       {% endfor %}
    </ul>
  </nav>

{% endblock %}